version: '2.2'

services:
  scrapy:
    build: .
    ports:
      - 12345
    depends_on:
      - rds
    volumes:
      - "/kindle:/kindle"
    command: bash -c "ls /novel && service cron start && crontab /novel/root && tail -f /novel/novel.log"
    tty: true
    restart: always



  rds:
    image: redis
    ports:
      - 6379
