version: '2.2'

services:
  scrapy:
    build: .
    ports:
      - 12345
    depends_on:
      - rds
    volumes:
      - "/kindle:/kindle"
    tty: true
    restart: always



  rds:
    image: redis
    ports:
      - 6379
